av_zone: [ap-northeast-1a, ap-northeast-1c, ap-southeast-1a, ap-southeast-1b, ap-southeast-2a,
  ap-southeast-2b, eu-central-1a, eu-central-1b, eu-west-1a, eu-west-1b, eu-west-1c,
  sa-east-1a, sa-east-1b, sa-east-1c, us-east-1a, us-east-1b, us-east-1c, us-east-1e,
  us-west-1a, us-west-1b, us-west-2a, us-west-2b, us-west-2c]
bid_ratio: [1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0]
down_rate: 20
in_gb: 0.0071
instance_type: c3.8xlarge
jobs_per: 4
num_jobs: [50, 100, 200, 500, 1000, 2000, 5000, 10000]
out_gb: 0.097
out_gb_dl: 0.097
proc_time: 399
product: Linux/UNIX
up_rate: 18
